### ISSUE TITLE
OutOfBound issue in 'readMedImg4CaffeCropNie4SingleS.py'

### ISSUE THREAD

**Issue by YilinLiu97** [ginobilinie/infantSeg#3]
Thank you for your great work! I'm sorry for bothering you such a silly question but I kept getting this error when using the readMedImg4CaffeCropNie4SingleS.py

> trainFA shape,  (10000, 1, 23, 23, 23)
matFA shape is  (287, 256, 256)
matFAOut shape is  (287, 256, 256)

Traceback (most recent call last):
  File "/Users/elaine/Desktop/infantSeg-master/readMedImg4CaffeCropNie4SingleS.py", line 137, in <module>
    main()
  File "/Users/elaine/Desktop/infantSeg-master/readMedImg4CaffeCropNie4SingleS.py", line 133, in main
    cubicCnt=cropCubic(mrimg,labelimg,dFA,step,rate)
  File "/Users/elaine/Desktop/infantSeg-master/readMedImg4CaffeCropNie4SingleS.py", line 92, in cropCubic
    trainFA[cubicCnt,0,:,:,:]=volFA #32*32*32
IndexError: index 10000 is out of bounds for axis 0 with size 10000
>

My input was just some random .nii files. 

Thanks in advance!

**Comment by YilinLiu97** [comment]
Never mind. solved!

**Comment by ginobilinie** [comment]
@YilinLiu97 
Sorry for the late response, it was night when you typed the questions. Feel free to contact me if you have any problems.

**Comment by YilinLiu97** [comment]
Hi @ginobilinie, thanks for the quick response. I do get another error when using checkHDF5.py:

> (19851, 1, 23, 23, 23)
()

Traceback (most recent call last):
  File "/Users/elaine/Desktop/infantSeg-master/checkHDF5.py", line 14, in <module>
    patchCT=npdataCT[20,0,:,:,:]
IndexError: too many indices for array
>>> 

The hdf5 file seems to be generated normally(didn't throw any error, at least), but when I tried to open it with matlab, I got "Unable to open. The file may be corrupted". Could you let me know what the problem may be? Thank you!

**Comment by ginobilinie** [comment]
what's your shape of your data when you write the hdf5?

**Comment by YilinLiu97** [comment]
(19851, 1, 23, 23, 23)

**Comment by YilinLiu97** [comment]
trainFA shape,  (14332296, 1, 23, 23, 23)
matFA shape is  (287, 256, 256)
matFAOut shape is  (287, 256, 256)

number of patches is 19851

**Comment by YilinLiu97** [comment]
It will also be great if there are demo codes available for training. My email: yliu469@wisc.edu
Your work will be a great help to mine! Thanks in advance.

**Comment by ginobilinie** [comment]
@YilinLiu97 What do you mean by demo codes for training? using caffe?

**Comment by YilinLiu97** [comment]
@ginobilinie never mind. please just ignore that request. What matters more to me is to make sure those patches were indeed generated.  Currently, 'readMedImg4CaffeCropNie4SingleS.py' works fine for me but 'CheckHdf5.py' fails. Could you possibly shed some light on this? The shape of my data fed into the codes are described above. I wish to get this working as soon as possible so I can cite your work. Thanks!

**Comment by ginobilinie** [comment]
@YilinLiu97  What's the print result of: 
"print npdataCT.shape"

And I have a suggestion for you: you can add several print shape setences to debug the code.

**Comment by YilinLiu97** [comment]
npdataMR.shape: (19851, 1, 23, 23, 23)
npdataCT.shape: () --- This must be the reason, but I'm not sure why this happens.

**Comment by ginobilinie** [comment]
you npdataCT is empty....which means you hdf5 is not well  generated.

I have uploaded the hpp file.
